# Display
CONFIG_DISPLAY=y

# FPU (M7 has single-precision hardware FPU)
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

# SDRAM / FMC
CONFIG_MEMC=y

# C library with math support
CONFIG_NEWLIB_LIBC=y

# Stack
CONFIG_MAIN_STACK_SIZE=8192

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
